export enum CardSet {
  ADVENTURES_AT_HOGWARTS = 'AAH',
  BASE_SET = 'BS',
  CHAMBER_OF_SECRETS = 'COS',
  DIAGON_ALLEY = 'DA',
  ECHOES_OF_THE_PAST = 'EOTP',
  HEIR_OF_SLYTHERIN = 'HOS',
  PRISONER_OF_ASKABAN = 'POA',
  QUIDDITCH_CUP = 'QC',
  STREETS_OF_HOGSMEADE = 'SOH',
}
